### ISSUE TITLE
Исправить шифт-правила в контейнерах

### ISSUE THREAD

**Issue by msifd** [GodMorduk/stew#2]
Пример ошибки: у шелфов всего 54 слота https://github.com/GodMorduk/stew/blob/91984359f2b22aba232f0eed5f27fd9cde9ce2b0/stewblocks/shelf.json#L39-L62
Из них:
- 18 (2 ряда по 9) - контейнер 
- 27 (3 ряда по 9) - инв перса
- 9 - хотбар перса

Следовательно в правилах нам нужно указать два случая:
- если тыкают на слоты от 0 до 17 (контейнер), то закидывать в слоты от 18 до 53.
- если тыкают на слоты от 18 до 53 (инв игрока), то закидывать в слоты от 0 до 17.

Однако в нашем случае скопипастили из примера с тремя рядами слотов и все эти числа сдвинулись на 9
https://github.com/GodMorduk/stew/blob/91984359f2b22aba232f0eed5f27fd9cde9ce2b0/stewblocks/shelf.json#L63-L72

И этот случай нужно исправить на 
```
"shiftClickRules": [
  {
    "from": [0, 17],
    "to": [18, 53]
  },
  {
    "from": [18, 53],
    "to": [0, 17]
  }
],
```
Также конечно нужно проверить все контейнеры

**Comment by msifd** [comment]
@Garddwr

**Comment by Garddwr** [comment]
gotovo
